server:
  port: 80

spring:
  application:
     name: cloud-order-service
  cloud:
    consul: #使用consul进行服务注册
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
